version: "3"
 
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    container_name: frontend
    build:
      context: ./salesPhase1-webapp
      dockerfile: Dockerfile

  frontend-admin:
    container_name: frontend-admin
    build:
      context: ./salesPhase1-admin
      dockerfile: Dockerfile

  backend:
    container_name: backend
    build:
      context: ./salesPhase1-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
